### ISSUE TITLE
Fails with perls < 5.16

### ISSUE THREAD

**Issue by andk** [athreef/Regexp-CharClasses-Helper#1]
Bisect leads to v5.15.6-494-gdc415b4. All perls after this commit pass the tests, all perls below it fail.

Best illustrated with the matrix:

http://matrix.cpantesters.org/?dist=Regexp-CharClasses-Helper%200.004

See also: https://rt.cpan.org/Ticket/Display.html?id=75132

HTH&&Thanks,

**Comment by a3f** [comment]
You're awesome. I will look into it.
Thanks :-)

**Comment by a3f** [comment]
Not sure if the module can be made with previous Perl versions without much change, but for now it has Perl `v5.15.7` as requirement. 

Thanks again for bisecting.
